# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51154ebddbdfa63579b95d2be84aab956c934df981f6b1ab1e91f1e8e7f65e457dd46a5bc27880fd146c881dd532b3392584eb0748688aaad18e830515e8dae9

test:
  secret_key_base: 44b2428533defb1463f9848c9ef4c035c7efc3e47330234c01316d33ebffa53c0f3ff9dd8cdc25ce9d474347efc485572bb560c76f64e9ccd21ffef8c88c466d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
